README.md

Slight improvement to the format and content of the project's readme

docs(README): improve readme by a smidge

---

shard.lock
spec/spec_helper.cr

adds support for custom online meeting URLs in google events
also returns the meeting URLs in the response objects

chore: bump dependencies

---

src/controllers/events.cr

feat(events): create visitor on check-in

---

src/controllers/guests.cr

tokenises on space and supports inverted commas fixes #101

feat(guests controller): improve search query

---

README.md
src/constants.cr

feat: add PG_CONNECTION_POOL_SIZE env

---

shard.lock
shard.override.yml

- Fix part of https://github.com/PlaceOS/staff-api/issues/106
- Will need retry logic for better performance but this would allow DB to refresh on ConnectionLost

build(shard): fix with latest crystal-db, crystal-pg and clear updates

---

src/controllers/events.cr

fix(events): on PUT request look up events with system mailbox

---

spec/controllers/bookings_spec.cr
src/models/booking.cr

fix(bookings): add validation for booking times

---

src/controllers/events.cr

after marking them as expected

fix(events update): unable to mark visitor as unexpected

---

shard.lock
shard.yml
spec/spec_helper.cr
src/models/tenant.cr

Closes #100 
Also uses updated version of Clear so all specs pass

feat(tenant): scopes in parameters for delegated access

---

spec/controllers/bookings_spec.cr
src/models/booking.cr

Closes PlaceOS/drivers/issues/268

fix(bookings): emails saved in lower case

---

spec/controllers/bookings_spec.cr
spec/controllers/events_spec.cr
spec/controllers/helpers/event_helper.cr
spec/fixtures/events/o365/create.json
spec/fixtures/events/o365/show_instance_recurring.json
spec/fixtures/events/o365/show_recurring.json
spec/fixtures/placeos/systems.json
spec/spec_helper.cr
src/controllers/events.cr
src/controllers/guests.cr

test(events): run pending tests

---

spec/controllers/bookings_spec.cr
src/controllers/bookings.cr
src/controllers/utilities/custom_converter.cr
src/migrations/0007_add_columns_and_update_bookings.cr
src/models/booking.cr

refactor(booking): use PlaceOS::Model::Email

---

shard.lock
shard.yml
spec/controllers/bookings_spec.cr
spec/spec_helper.cr
src/controllers/bookings.cr
src/migrations/0014_add_history_to_bookings.cr
src/models/booking.cr
src/models/booking/history.cr

Add current_state and history to the Booking controller and Booking model.

feat(bookings): add current_state and history

---

shard.lock
shard.yml
spec/controllers/bookings_spec.cr
src/controllers/bookings.cr
src/migrations/0015_add_department_to_bookings.cr
src/models/booking.cr
src/models/tenant.cr

and allow it to be queried
Closes #147

feat(bookings): add department field

---

spec/controllers/bookings_spec.cr
spec/controllers/events_spec.cr
spec/controllers/guests_spec.cr
spec/models/tenant_spec.cr
spec/spec_helper.cr

- Replaces hard coded data inputs with randomised values
- Refactor some duplicated code
- Improve Webmocks
**Benefits**
Ensures code is tested differently each time spec is run therefore making the spec more reliable 
**Possible drawbacks**
n/a
**Applicable issues**
- Closes #153

refactor(spec): randomise data

---

shard.lock
shard.yml
src/controllers/application.cr
src/models/tenant.cr

Bumps `placeos-models` for `JSON::Serializable` support

build: bump `placeos-models`

---

spec/controllers/bookings_spec.cr
src/controllers/bookings.cr

Change the booking limits to be for overlapping zones instead of global

feat(bookings): restrict booking_limits by zones

---

src/controllers/tenants.cr

shouldn't update credentials unless they are provided

fix(controllers/tenants): update to support limits

---

spec/controllers/bookings_spec.cr
src/controllers/bookings.cr

Corrects logic mistakes made in previous feature update (https://github.com/PlaceOS/staff-api/pull/166)

fix(bookings): correct logic

---

spec/controllers/calendars_spec.cr

Adds missing test for new `/free_busy` functionality

test(calendars): missing free/busy spec

---

shard.lock
spec/controllers/calendars_spec.cr
spec/controllers/events_spec.cr
spec/controllers/guests_spec.cr
spec/controllers/helpers/event_helper.cr

- Pulls in PlaceOS/calendar & PlaceOS/office365 API changes
- Changes URLs in WebMocks to encode special characters

test: update WebMock with encoded URLs

---

shard.lock
src/controllers/events.cr

feat(controllers/events): add support for declining events

---

src/migrations/0017_migrate_user_id.cr

so reporting and ownership of bookings is not lost

feat(migrations/migrate_user_ids): add user_id migrations

---

Dockerfile
docker-compose.yml
shard.lock
spec/models/tenant_spec.cr
src/controllers/tenants.cr
src/controllers/utilities/multi_tenant.cr
src/migrations/0018_add_delegated_to_tenants.cr
src/models/tenant.cr

feat: add support for delegated API access

---

shard.lock
spec/controllers/group_spec.cr
spec/fixtures/groups/index.json
spec/fixtures/groups/index_filtered.json
spec/fixtures/groups/show.json
src/controllers/application.cr
src/controllers/groups.cr
src/controllers/staff.cr
src/error.cr

so we can build a delegated access calendar driver

feat: add group related routes

---

src/controllers/events.cr

should be updating the host event

fix(events): update on graph api where host event switch not made

---

shard.lock
spec/controllers/events_spec.cr
spec/fixtures/events/o365/events_query.json
src/controllers/events.cr

plus performance improvements to update method

feat(events): add dedicated metadata update methods

---

spec/controllers/bookings_spec.cr
src/models/booking.cr

Adds a state transition for checked in -> cancelled.
**Benefits**
It will allow cancelling a booking after checking in.

feat(bookings): checked_in to canclled state transition

---

src/controllers/calendars.cr

so the calendars match on the results

fix(calendar): downcase candidate keys

---

Dockerfile
src/controllers/utilities/placeos-helpers.cr

so emails can easily be matched in the systems lookup hash provided

fix(utilities/helpers): ensure emails are downcased

---

src/controllers/bookings.cr
src/migrations/0001_create_tenant.cr
src/migrations/0002_create_event_metadata.cr
src/migrations/0003_create_guest.cr
src/migrations/0004_create_attendee.cr
src/migrations/0005_create_bookings.cr
src/migrations/0006_add_columns_to_event_metadata.cr
src/migrations/0007_add_columns_and_update_bookings.cr
src/migrations/0008_add_timestamps_to_bookings.cr
src/migrations/0009_add_timestamps_to_booking_events.cr
src/migrations/0010_rename_ext_column.cr
src/migrations/0011_associate_attendee_with_booking.cr
src/migrations/0012_add_deleted_at_and_email_digest.cr
src/migrations/0013_add_booking_limits_tenants.cr
src/migrations/0014_add_history_to_bookings.cr
src/migrations/0015_add_department_to_bookings.cr
src/migrations/0016_add_unique_constraint.cr
src/migrations/0017_migrate_user_id.cr
src/migrations/0018_add_delegated_to_tenants.cr
src/migrations/0019_add_event_id_to_bookings.cr
src/models/booking.cr

fixes compiler warnings and resolves #172

feat(bookings): add event_id column for associating bookings to events

---

shard.lock
spec/controllers/events_spec.cr
src/controllers/application.cr
src/controllers/events.cr
src/models/event.cr

allows the frontend to hint at event features when viewing the users calendars

feat(events): relax when metadata is returned on events

---

shard.lock
src/controllers/bookings.cr
src/controllers/calendars.cr
src/controllers/events.cr
src/controllers/guests.cr
src/controllers/tenants.cr

feat(tenants): expose if running in delegated mode

---

shard.lock

improve all day event generation

chore(shard.lock): bump office365 lib

---

OPENAPI_DOC.yml
spec/models/tenant_spec.cr
src/controllers/calendars.cr
src/controllers/events.cr
src/controllers/tenants.cr
src/controllers/utilities/placeos-helpers.cr
src/migrations/0020_add_service_account_to_tenants.cr
src/models/tenant.cr

ignoring the user accounts making the requests

feat: add support for running using a service account

---

src/controllers/events.cr

where no meta exists currently

fix(events): patching extension metadata

---

OPENAPI_DOC.yml
spec/controllers/bookings_spec.cr
spec/controllers/calendars_spec.cr
src/controllers/bookings.cr
src/controllers/events.cr
src/controllers/tenants.cr
src/models/attendee.cr
src/models/booking.cr
src/models/guest.cr
src/models/tenant.cr

when it comes to standalone attendees

fix(bookings): improve consistency between requests and responses

---

.gitignore
OPENAPI_DOC.yml
shard.lock
shard.override.yml
shard.yml
spec/controllers/helpers/survey_helper.cr
spec/controllers/surveys/questions_spec.cr
spec/controllers/surveys_spec.cr
src/controllers/surveys.cr
src/controllers/surveys/answers.cr
src/controllers/surveys/invitations.cr
src/controllers/surveys/questions.cr
src/migrations/0023_add_answer_json_to_survey_answers.cr
src/migrations/0024_create_survey_invitation.cr
src/models/survey.cr
src/models/survey/answer.cr
src/models/survey/invitation.cr
src/models/survey/question.cr

- add json field to answers
- add answer data endpoints
- unique token (for invite url)

feat(surveys): survey improvements

---

.ameba.yml
shard.lock
src/controllers/calendars.cr
src/controllers/events.cr
src/controllers/utilities/current-user.cr
src/models/event.cr
src/models/tenant.cr

adds additional documentation to the source code
adds event details to the change signals

feat(events): improve event patching

---

Dockerfile
OPENAPI_DOC.yml
src/controllers/events.cr

update docs with more information on moving rooms

fix(events): regression caused by missing calendar id

---

OPENAPI_DOC.yml
shard.lock
src/controllers/application.cr
src/controllers/events.cr
src/models/event_metadata.cr

feat(event_metadata): provide additional options for metadata queries

---

src/controllers/events.cr

FYI - currently available as the `nightly` tag for testing on tonights call

feat(events): decorate events with system data where possible

---

OPENAPI_DOC.yml
shard.lock
src/controllers/staff.cr

depends on https://github.com/PlaceOS/calendar/pull/21

feat(staff): [PPT-89] support Azure AD filter

---

src/controllers/tenants.cr
src/models/tenant.cr

as defaults to false otherwise

fix(tenants): enable patching delegated state

---

shard.lock
src/controllers/application.cr

also fixes an race condition related to the redis pool however this issue probably does not effect staff-api

fix: bump forbidden log levels

---

OPENAPI_DOC.yml
docker-compose.yml
spec/controllers/helpers/booking_helper.cr
spec/controllers/surveys/triggers_spec.cr
src/migrations/0030_alter_enum_trigger_type.cr
src/models/attendee.cr
src/models/survey.cr

add visitor triggers to surveys
- `VISITOR_CHECKEDIN`
- `VISITOR_CHECKEDOUT`

feat(survey): [PPT-358] add visitor triggers

---

shard.lock
spec/controllers/bookings_spec.cr
spec/controllers/helpers/booking_helper.cr
src/controllers/bookings.cr

chore: add linked booking to event spec

---

shard.lock
spec/controllers/events_spec.cr
src/controllers/application.cr
src/controllers/events.cr
src/controllers/utilities/multi_tenant.cr

Bookings driver will use this to notify of updates

feat(events): add push event endpoint

---

shard.lock
src/controllers/events.cr

instead of absolute days
also PPT-645 and PPT-666

fix(events): use relative monthly bookings by default (PPT-651)

---

src/controllers/bookings.cr
src/controllers/events.cr

fix(events): check not required with delegated access PPT-758

---

src/controllers/calendars.cr

More hacky fixes for timeslot availability (https://github.com/PlaceOS/staff-api/pull/289)

fix(calendar): availability check

---

src/controllers/events.cr

also add additional access confirmations

feat(events): skip some checks when in delegated mode

---

src/controllers/utilities/multi_tenant.cr

fix: return unauthorized if delegated access has expired [PPT-731]

---

spec/controllers/calendars_spec.cr
src/controllers/calendars.cr

ensure we return available items

fix(calendars): availability removing busy items within period

---

OPENAPI_DOC.yml
src/controllers/bookings.cr
src/controllers/events.cr

makes the following changes:
* fixes cancelling bookings in concierge
* fixes linked bookings not being deleted when an event is cancelled
* provides a strict response option for modifying the event query response where there are errors

feat(events): provide strict requirements for processing responses [PROJ-433] [PROJ-420] [PPT-975]

---

src/controllers/events.cr

https://github.com/PlaceOS/calendar/pull/25

feat(events): add filter to index

---

OPENAPI_DOC.yml
shard.lock
src/controllers/application.cr
src/controllers/calendars.cr
src/controllers/events.cr
src/controllers/groups.cr
src/controllers/guests.cr
src/error.cr
src/models/event.cr

optionally locks requests from particular users to ensure serialised access and prevent MS from rate limiting users

feat(events): serialize requests from each user [PROJ-512]

---

OPENAPI_DOC.yml
shard.lock
spec/controllers/events_spec.cr
spec/controllers/helpers/event_helper.cr
src/controllers/application.cr
src/controllers/events.cr

also resolves linked booking rejection on meeting rejection

fix(events): recurring metadata visibility [PPT-1072] [PPT-1073]

---

shard.lock
src/controllers/bookings.cr

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

fix(bookings): ensure serialisable transactions

---

OPENAPI_DOC.yml
spec/controllers/bookings_spec.cr
spec/controllers/tenants_spec.cr
src/controllers/tenants.cr

endpoints for getting/setting the `early_checkin` value

feat(tenants): early_checkin endpoints

---

src/controllers/bookings.cr

requires https://github.com/PlaceOS/drivers/pull/531 to actually do anything with the signals

feat(bookings): [PPT-1430] signal on induction accepted/declined

---

OPENAPI_DOC.yml
shard.lock
spec/controllers/bookings_spec.cr
src/controllers/bookings.cr
src/controllers/events.cr

for use with drivers that may need to track if bookings have been sync'd

feat(bookings): add method for patching extension data
