PlaceOS/staff-api

src/controllers/guests.cr

resolves #95
making it nilable is not really possible given the design.
The entry should be deleted or a dummy email assigned

feat(guests controller): make email mutable

---

spec/controllers/events_spec.cr

Resolves error triggering spec failure when build against crystal nightly.

fix: syntax error in specs

---

.github/workflows/ci.yml
Dockerfile

- Removes extraneous dependencies in `Dockerfile`
- Sets crystal version to 1.1.1
- Extends CI matrix to continue when a job in the matrix is unstable.

Update CI matrix and Dockerfile to 1.1.1

---

spec/controllers/events_spec.cr
src/controllers/events.cr
src/models/event_metadata.cr

Closes place-technology/suncorp-ntt/issues/151

feat(events): endpoint to get events by ext_data

---

src/controllers/events.cr

fix(event/guests): Don't add host as guest, even when event.host is not specified
without this change, line #110 does not correctly filter out the host from attendees[] because of email string case mismatch

fix(event/guests): Don't add host as guest, even when event.host is not specified

---

spec/controllers/bookings_spec.cr
spec/controllers/calendars_spec.cr
src/controllers/bookings.cr
src/migrations/0005_create_bookings.cr
src/migrations/0007_add_columns_and_update_bookings.cr
src/models/booking.cr

feat(bookings): flag on delete

---

spec/controllers/bookings_spec.cr

test(bookings): returns query for current user when no user or zone is specified

---

spec/controllers/bookings_spec.cr
spec/models/tenant_spec.cr
src/controllers/bookings.cr
src/migrations/0013_add_booking_limits_tenants.cr
src/models/tenant.cr

Add configurable booking limits.

feat(bookings): add configurable limits on booked assets

---

src/controllers/events.cr
src/models/booking.cr

Tiny perf catch regarding iteration.
- Sets a better guess for the initial capacity of two collections
- Avoids an unnecessary `map` with an `each`
**Benefits**
Small memory and speed boost.

perf: avoid unnecessary allocation

---

spec/controllers/bookings_spec.cr
spec/controllers/tenants_spec.cr
src/controllers/bookings.cr
src/controllers/tenants.cr
src/controllers/utilities/multi_tenant.cr

- return booking_limits in #index
- add #current_limits, #show_limits, #update_limits
- add `limit_override` query param to Bookings #create and #update

feat(tenants): expose booking limits in the API

---

spec/controllers/bookings_spec.cr
src/controllers/bookings.cr

- Considers `checked_out_at` as the true booking end time when creating new bookings, updating existing bookings and checking into bookings
- Allows early check in on the same day if no other booking fall between current time and end of booking
- Prevents check in & approval actions being performed on deleted bookings
**Benefits**
Aligns booking behaviour with real world logic
**Applicable issues**
Closes #165

feat(bookings): update booking validation

---

shard.lock
spec/controllers/bookings_spec.cr
spec/controllers/calendars_spec.cr
spec/controllers/guests_spec.cr
src/controllers/bookings.cr
src/controllers/calendars.cr

`/free_busy` controller now calculates the duration between given times and if this value is greater than 5 minutes it will use this as the free/busy availability interval else it will return a `400` error
**Benefits**
- Allows bookings that are less than 30 minutes to be booked
- free/busy information is now more exact
**Applicable issues**
Closes https://github.com/PlaceOS/office365/issues/29

feat(calendars): precise free/busy availability requests

---

spec/controllers/bookings_spec.cr
src/controllers/application.cr
src/controllers/bookings.cr
src/error.cr

Changes the error code for for reaching the booking limit to 410.
**Benefits**
Differentiates between a booking conflict and a booking limit error.

feat(booking): change error code on booking limits

---

spec/controllers/bookings_spec.cr
src/controllers/bookings.cr

- checkout, delete (don't check limit)
- check-in (check limit only if already checked out)
- patch (don't check limit unless start and end range is modified outside of the current range)
- allow changes to start and end times if the range is within the bounds of the old range
- Checked out bookings should not be counted when determining if the user has hit the booking limit

feat(bookings): adjust booking limit checks

---

src/constants.cr

Aligns `APP_NAME` with other service's lowercased kebab cased names
**Benefits**
Consistency with other services

refactor: set app name to `staff-api`

---

Dockerfile
docker-compose.yml
shard.lock
spec/controllers/events_spec.cr
src/controllers/application.cr
src/controllers/bookings.cr
src/controllers/events.cr
src/controllers/guests.cr
src/controllers/utilities/multi_tenant.cr
src/models/event_metadata.cr

reduces reliance on obtaining the host event when running against office365

fix(visitor_checkin): when running in delegated permissions mode

---

shard.lock
shard.override.yml
spec/models/tenant_outlook_config_spec.cr
src/controllers/outlook.cr
src/models/outlook_manifest.cr
src/models/tenant.cr
src/models/tenant/outlook_config.cr

- set version to a timestamp of when the config was changed
- treat blank strings as nil (use the default config)
- move VersionOverrides
- set bt:Sets min version to 1.6

fix(outlook): minor manifest fixes

---

src/models/tenant.cr

as Nil is a valid conference type, but the default is set if the key is not provided by the frontend

fix(tenant): don't set a default conference type

---

OPENAPI_DOC.yml
src/controllers/outlook.cr
src/models/tenant/outlook_config.cr

The version must be specified in this format `1.0.0.01` and be incremented when configuring it.

fix(outlook): xml manifest version

---

OPENAPI_DOC.yml
spec/controllers/surveys/answers_spec.cr
spec/controllers/surveys/invitations_spec.cr
spec/controllers/surveys/questions_spec.cr
spec/controllers/surveys/triggers_spec.cr
spec/controllers/surveys_spec.cr
src/controllers/surveys/questions.cr
src/migrations/0028_add_deleted_at_to_questions.cr
src/models/survey/question.cr

Get endpoint for survey questions:
Update endpoint for survey questions:
Delete endpoint for survey questions:

feat(survey): [PPT-67|PPT-101] update /surveys/questions endpoint

---

shard.lock
src/constants.cr

in addition to being able to use `PG_DATABASE_URL` you can now use
* `PG_HOST`
* `PG_PORT`
* `PG_DB`
* `PG_USER`
* `PG_PASSWORD`
* `PG_QUERY`

feat(db): support additional connection details

---

OPENAPI_DOC.yml
shard.lock
src/controllers/events.cr

so that office365 users can lookup metadata without making requests to get events. this is faster and works around issues related to delegated access to resources

feat(events): patch metadata lookup using ical uid

---

shard.lock

so `user.email == provided_email.downcase` will always work

fix(shard.lock): bump models for JWT email downcasing

---

src/controllers/bookings.cr

need to ensure no overlapping bookings

revert(bookings): add back transaction

---

OPENAPI_DOC.yml
shard.lock
spec/controllers/events_spec.cr
src/controllers/events.cr

hence it requires to use a special function on the client. This is not true for Google, hence this went unnoticed

fix(events): accepting an event must use a special route

---

shard.lock
spec/controllers/bookings_spec.cr
spec/controllers/calendars_spec.cr
spec/controllers/events_spec.cr
spec/controllers/helpers/event_helper.cr
spec/spec_helper.cr
src/controllers/bookings.cr
src/controllers/events.cr
src/controllers/utilities/current-user.cr
src/controllers/utilities/placeos-helpers.cr

group checks no longer rely on the JWT and check the database added permissions to event metadata, queries and updates

feat: improve permissions checks

---

spec/controllers/events_spec.cr
src/controllers/bookings.cr

to prevent skipping new bookings created during pagination

fix(bookings): pagination using created ascending order

---

shard.lock
src/controllers/events.cr

so we can differentiate why something was cancelled

feat(events): add a reason for cancellation

---

docker-compose.yml
shard.lock
src/controllers/events.cr

when making index requests to ensure the correct data is returned in otherwise possibly ambiguous situations

feat(events): preference metadata and system selection

---

shard.lock
spec/controllers/bookings_spec.cr
spec/controllers/events_spec.cr
spec/controllers/recurring_bookings_spec.cr
src/controllers/guests.cr

feat: PPT-54 updated guests endpoint to use  full text search capabilities
